Auto generate through doAutoReconf.sh

diff --git a/proxytest/trunk/configure b/proxytest/trunk/configure
--- a/proxytest/trunk/configure
+++ b/proxytest/trunk/configure
@@ -3340,15 +3340,58 @@ else
 fi
 
 
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+cat >conftest.$ac_ext <<_ACEOF
+int main(){return 0;}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+{ { echo "$as_me:$LINENO: error: Could not run C++ compiler
+See \`config.log' for more details." >&5
+echo "$as_me: error: Could not run C++ compiler
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+CFLAGS=""
+CXXFLAGS=""
+
 if test "x$GCC" = "xyes" ; then
-   CPPFLAGS="-Wall -D_REENTRANT"
+   CFLAGS="-Wall -D_REENTRANT"
+   CXXFLAGS=$CFLAGS
 else
    echo "You need the GNU C Compiler to compile proxytest."
    exit
 fi
 
-CFLAGS=""
-CXXFLAGS=""
 LIBS="$LIBS -L/usr/lib -L/usr/local/lib"
 
 case "$host" in
@@ -5178,7 +5221,6 @@ fi;
 XMLINCLUDEFLAGS="-I/usr/include/xercesc -I$xmlincludedir -I$xmlincludedir/xercesc"
 CFLAGS="$CFLAGS $XMLINCLUDEFLAGS"
 CXXFLAGS=$CFLAGS
-
 echo "$as_me:$LINENO: checking for dom/DOM.hpp" >&5
 echo $ECHO_N "checking for dom/DOM.hpp... $ECHO_C" >&6
 if test "${ac_cv_header_dom_DOM_hpp+set}" = set; then
