Auto generate through doAutoReconf.sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5624,7 +5624,14 @@ echo "$as_me:$LINENO: result: $ac_cv_func_epoll_wait" >&5
 echo "${ECHO_T}$ac_cv_func_epoll_wait" >&6
 if test $ac_cv_func_epoll_wait = yes; then
 
-	    cat >conftest.$ac_ext <<_ACEOF
+	    if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -5634,28 +5641,17 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int handle;handle=epoll_creat(1);if(handle==-1)exit(-1);
+int handle;handle=epoll_create(1);if(handle==-1)exit(-1);
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -5669,18 +5665,17 @@ _ACEOF
 
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 
 fi
-{ { echo "$as_me:$LINENO: error: stop" >&5
-echo "$as_me: error: stop" >&2;}
-   { (exit 1); exit 1; }; }
+
+fi
 echo "$as_me:$LINENO: checking whether TCP_KEEPALIVE is declared" >&5
 echo $ECHO_N "checking whether TCP_KEEPALIVE is declared... $ECHO_C" >&6
 if test "${ac_cv_have_decl_TCP_KEEPALIVE+set}" = set; then
