Auto generate through doAutoReconf.sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11466,133 +11466,59 @@ for xmldir in "" $tryxmlincludedir ; do
 	CFLAGS="$saved_CFLAGS -I$xmldir -I$xmldir/xercesc"
 	CXXFLAGS="$saved_CXXFLAGS -I$xmldir -I$xmldir/xercesc"
 	echo $CXXFLAGS
-	if test "${ac_cv_header_dom_DOM_hpp+set}" = set; then
-  { echo "$as_me:$LINENO: checking for dom/DOM.hpp" >&5
-echo $ECHO_N "checking for dom/DOM.hpp... $ECHO_C" >&6; }
-if test "${ac_cv_header_dom_DOM_hpp+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_dom_DOM_hpp" >&5
-echo "${ECHO_T}$ac_cv_header_dom_DOM_hpp" >&6; }
+	if test "$cross_compiling" = yes; then
+
+			found_xmldir=1
+			echo "skip xml include run test because of cross compiling"
 else
-  # Is the header compilable?
-{ echo "$as_me:$LINENO: checking dom/DOM.hpp usability" >&5
-echo $ECHO_N "checking dom/DOM.hpp usability... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_includes_default
-#include <dom/DOM.hpp>
+
+				#include <dom/DOM.hpp>
+				int main(void)
+				{
+	return 0;
+				}
+
 _ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
   *) ac_try_echo=$ac_try;;
 esac
 eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
+  (eval "$ac_link") 2>&5
   ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_header_compiler=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6; }
-
-# Is the header present?
-{ echo "$as_me:$LINENO: checking dom/DOM.hpp presence" >&5
-echo $ECHO_N "checking dom/DOM.hpp presence... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <dom/DOM.hpp>
-_ACEOF
-if { (ac_try="$ac_cpp conftest.$ac_ext"
-case "(($ac_try" in
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
   *) ac_try_echo=$ac_try;;
 esac
 eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  (eval "$ac_try") 2>&5
   ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null && {
-	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       }; then
-  ac_header_preproc=yes
+  (exit $ac_status); }; }; then
+
+				found_xmldir=1
+				break;
+
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-  ac_header_preproc=no
-fi
+( exit $ac_status )
 
-rm -f conftest.err conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6; }
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: present but cannot be compiled" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: dom/DOM.hpp:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: dom/DOM.hpp:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: dom/DOM.hpp: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: dom/DOM.hpp: in the future, the compiler will take precedence" >&2;}
-
-    ;;
-esac
-{ echo "$as_me:$LINENO: checking for dom/DOM.hpp" >&5
-echo $ECHO_N "checking for dom/DOM.hpp... $ECHO_C" >&6; }
-if test "${ac_cv_header_dom_DOM_hpp+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_dom_DOM_hpp=$ac_header_preproc
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_dom_DOM_hpp" >&5
-echo "${ECHO_T}$ac_cv_header_dom_DOM_hpp" >&6; }
 
 fi
-if test $ac_cv_header_dom_DOM_hpp = yes; then
-  found_xmldir=1 break;
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 
 
