Auto generate through doAutoReconf.sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13306,6 +13306,65 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+    { echo "$as_me:$LINENO: checking whether MYSQL_OPT_RECONNECT is declared" >&5
+echo $ECHO_N "checking whether MYSQL_OPT_RECONNECT is declared... $ECHO_C" >&6; }
+if test "${ac_cv_have_decl_MYSQL_OPT_RECONNECT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    				#ifdef HAVE_MYSQL_MYSQL_H
+				#include <mysql/mysql.h>
+				#elif defined(HAVE_MYSQL_H)
+				#include <mysql.h>
+				#endif
+
+
+int
+main ()
+{
+#ifndef MYSQL_OPT_RECONNECT
+  (void) MYSQL_OPT_RECONNECT;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_have_decl_MYSQL_OPT_RECONNECT=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_have_decl_MYSQL_OPT_RECONNECT=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_have_decl_MYSQL_OPT_RECONNECT" >&5
+echo "${ECHO_T}$ac_cv_have_decl_MYSQL_OPT_RECONNECT" >&6; }
 
 LIBS="$saved_LIBS"
 fi
