Auto generate through doAutoReconf.sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5634,7 +5634,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int handle;handle=epoll_create(1);if(handle==-1)exit(1);
+int handle;handle=epoll_create(1);if(handle==-1)exit(-1);
   ;
   return 0;
 }
@@ -5678,6 +5678,9 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 
 fi
+{ { echo "$as_me:$LINENO: error: stop" >&5
+echo "$as_me: error: stop" >&2;}
+   { (exit 1); exit 1; }; }
 echo "$as_me:$LINENO: checking whether TCP_KEEPALIVE is declared" >&5
 echo $ECHO_N "checking whether TCP_KEEPALIVE is declared... $ECHO_C" >&6
 if test "${ac_cv_have_decl_TCP_KEEPALIVE+set}" = set; then
