Auto generate through doAutoReconf.sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10424,6 +10424,75 @@ fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 
+echo "$as_me:$LINENO: checking if libxerces-depdom is needed" >&5
+echo $ECHO_N "checking if libxerces-depdom is needed... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include "util/XercesDefs.hpp"
+#include "util/PlatformUtils.hpp"
+#if (XERCES_VERSION_MAJOR >1)
+    #include <dom/deprecated/DOM.hpp>
+    #include <dom/deprecated/DOMParser.hpp>
+#else
+    #include <dom/DOM.hpp>
+    #include <parsers/DOMParser.hpp>
+#endif
+#if (_XERCES_VERSION >= 20200)
+    XERCES_CPP_NAMESPACE_USE
+#endif
+
+int
+main ()
+{
+XMLPlatformUtils::Initialize();		DOM_Document doc=DOM_Document::createDocument();
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: No" >&5
+echo "${ECHO_T}No" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: Yes" >&5
+echo "${ECHO_T}Yes" >&6
+LIBS="$LIBS libxerces-depdom"
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
